stages:          # List of stages for jobs, and their order of execution
  - create-rpm

create-rpm-job:       # This job runs in the build stage, which runs first.
  stage: create-rpm
  tags:
    - ood
  script:
    - git-build-rpm -S -N "Compen CI" -K $OOD_CI_SIGN_PASS -U -L https://ood-repo.rahtiapp.fi/add_rpm
    - echo "RPM build done."
