stages:          # List of stages for jobs, and their order of execution
  - create-rpm

create-rpm-job:       # This job runs in the build stage, which runs first.
  stage: create-rpm
  tags:
    - ood
  script:
    - git-build-rpm
    - rpmsign --addsign *.rpm
    - cp *.rpm $HOME/RPMS
    - echo "RPM build done."
