stages:          # List of stages for jobs, and their order of execution
  - create-rpm

create-rpm-job:       # This job runs in the build stage, which runs first.
  stage: build-rpm
  tags:
    - ood
  script:
    - git-build-rpm
    - env | grep OOD_
    - echo "RPM build done."
